# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#     - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.


version: '3.8'

services:

  db:
    image: postgres:16
    container_name: bank_bd_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bank_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bank_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

volumes:
  postgres_data:











